### ISSUE TITLE
High Score and Top Level does not display

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#112]
**Bug**
When selecting level paths, no one knows that Austin has all the high scores.

**Expected Behavior**
It should display the correct score and top level for each individual level path

**Steps to Reproduce**
1. Go to any branch or repository
2. Proceed to the level path selection menu

**Comment by Regulator13** [comment]
I do not have this issue @afrey15. I see all the high scores and top levels.

**Comment by afrey15** [comment]
Dang. This is surely related to the fact that `space` is STILL my climb key as well. I've deleted all the 'ini' files. There must be something else I need to reset but I can't seem to find it.

**Comment by Regulator13** [comment]
Maybe deleting them messed them up? Idk how @Phabbits handled the files

**Comment by afrey15** [comment]
They are cache files, so they are automatically replaced if they aren't found at the start of the program. It must be something in the current code...

**Comment by Regulator13** [comment]
Are you still having the issue @afrey15? Now that we fixed the climb issue and it wasn't that.
