### ISSUE TITLE
Fireball and iceball throwing distance

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#126]
**Context** 
We have now corrected scale on almost every game element. For the most part, your focus area is defined by how far you can jump and throw which are pretty close to each other. Fireballs and iceballs are a weird exception. Also, without lasers, you are often trying to hit a target that is closer. The extra distance is often more of a hindrance than a help.

**Idea**
Make the fireballs and iceballs throw the same, or a few inches more than the distance of a block. This will be more in line with character abilities.

**Comment by Regulator13** [comment]
Looking through the new issues this is probably the one I agree with the least (still). Now before changing this would be very easy but it will be more difficult now due to a few things:

1. The idea that weight will not affect distance means I can't just make them super heavy so they don't go far
2. The gun item means I can't just destroy them after they travel one block, nor do I really want to as I liked being able to plan a nice arc shot.

That being said while I think this is worth a test, it won't be the first change.

**Comment by Regulator13** [comment]
Really I don't think they shoot far enough as is. Hitting patrols and platforms tough enough already. I mean think about it, if the player can only shoot 1 block, why does it matter the vertical platforms come down 3 blocks (which I think was a great addition btw) ? 

Furthermore the players can throw blocks 2 or 3 big blocks, if we reduced fireballs we'd have to reduce block throwing (realistically more than the fireball) and it would take forever to get anywhere. I vote no on this change and think we should keep the distance as is.

**Comment by afrey15** [comment]
I hear you. But hitting patrols and platforms has often been hard for me just because of how far these things go. If we reduce them to 2-3 blocks players will still be able to hit all vertical platforms. At the same time, it will increase the value of the gun item immensely. It needs more situations where it is useful anyway. Blocks do not need to realistically be reduced more either. They can throw them the same distance. There is no weight to these balls of magic to begin with. There can't be expectations that they should be "thrown" further.

**Comment by Regulator13** [comment]
But making them not shoot as far will make it _harder_ not easier to hit stuff. You'll have to right next to stuff. I see your logic, I just don't agree with the change.

**Comment by afrey15** [comment]
The firing distance is just ridiculous though. 90% of the time, I don't need them to go as far as they do. All the time, I wonder, why can my character shoot halfway across the map? And 10% of the time when I am grateful for the firing distance, I wonder why we have a gun at all if I can hit almost everything I want to without it.

**Comment by Regulator13** [comment]
It turns out in a bug I just fixed that we were using the weakest character, the nutcracker, (instead of the grinch) to test things so I will increase the mass of the fire/iceball to be the same as the blocks

**Comment by afrey15** [comment]
Good. To. Know.

**Comment by Regulator13** [comment]
The firing distance was lowered to 3 blocks max. Will that satisfy this issue? I think it's a pretty good distance now.

**Comment by afrey15** [comment]
Yes! Seems good
