### ISSUE TITLE
Holding left and right over keys to activate ledge hanging

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#130]
**Context** 
There is one mechanic that caused a lot of trouble during the playtest. The need to be pressing the left or right over key in order to catch on a ledge caused both Gabe and I some confusion and trouble as we climbed up the ledges as well.

**Idea**
Make it so that character's will attach to the top of a ledge automatically. This does not need to be the case for climbing with climbing picks but at least with the ledge hanging. Make it so that players will fall a couple pixels out from the edge when they press the down arrow, so that they can still fall. Finally, if the distance to the top of a ledge is such that the player with the lowest jump variable can still jump to the top without using ledge climbing, feel free to make it so that player's will not attach to ledges in those instances.

**Comment by Regulator13** [comment]
This sounds good, and the last thing is already implemented!
