### ISSUE TITLE
Energy spawns can appear inside of blocks

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#132]
**Context** 
Energy spawns that spawn on top of a block are technically still reachable, but it sure looks like a glitch.

**Idea**
Make it so that energy spawns will not appear on top, or behind blocks.

**Comment by Regulator13** [comment]
This should not be happening anymore after the last fix, did you see this since the most recent update?

**Comment by afrey15** [comment]
Hrmm
