### ISSUE TITLE
Direction changes in mid-air

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#146]
**Context** 
I've been thinking a lot about direction changes in air and about the water drop climbing phenomenon and I believe I have the solution.

**Idea**
Make it impossible to change directions in mid-air

**Reasoning**
You can't change directions in the air in real life, why should our game allow it.

**Implementation**
Prevent players from turning around while they are in the air. Make it so that pressing the opposite directional arrow of the way you are jumping will only slow you down until you falling straight down. Prevent the sprite display from changing directions also. Make full commitment to the direction you jump.

**Comment by Regulator13** [comment]
My vote on this is no. I get improving realism but we have to draw the line somewhere. It's not like people can actually slow themselves to a stop in mid-air or jump 4 times their height. I think drag helped this but eliminating it completely will just make the game frustrating. To answer your question, we should allow it because its fun.

**Comment by afrey15** [comment]
Wrap around climbing is a serious problem though. It does need to be addressed. This idea is the third piece to my jumping solution -- single jumps and drag being the first two pieces. I agree with drawing a line. I think the line should be all-in or nothing. We aren't doing anyone any favors with mostly realistic. Jumping four times your height is different in that if you were strong it is plausible, where changing directions in mid-air looks more like a flaw in the physics system.

**Comment by afrey15** [comment]
We all do. Except when your a new player, you think you're about to drown, and your teammates pull off a maneuver so difficult and unwieldy that you can't help but believe they are cheating and breaking the game.

**Comment by Regulator13** [comment]
But this is just a maneuver. Having it does allow cool stuff for more advanced players, but it doesn't hurt beginners, it helps them. Like when they make a jump up to a moving horizontal platform over a cliff but miss the timing. With this they'd just be screwed if they didn't time it perfectly. Right now they can turn back and try again. Our game is already kinda hard and this will make it much harder

**Comment by afrey15** [comment]
Hard disagree. Even current players will quickly adjust and quickly learn to be more careful with their jumps. I think it will hardly be commented on except that the physics feel more realistic. This is a "stop and think" mechanic, promoting planning and strategy in the game. If you want forgiveness for timing a jump wrong, you should be thinking about checkpoints or other solutions. Note that you already created stops for moving platforms to vastly help alleviate this problem. Pulling back on an poorly timed jump is not something that player's need, and once you take it out, you'll realize it's not even something you really wanted.

**Comment by Regulator13** [comment]
I'll think about this. Maybe I can give it a test implementation

**Comment by afrey15** [comment]
Should you do so, I really think you'll like the way it changes your perspective when jumping.

**Comment by Regulator13** [comment]
Bruh. Check the wiki. I've been busy
