### ISSUE TITLE
On network games, characters will sometimes lose left/right movement

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#154]
**Bug**
Sometimes, active players will lose the ability to move left or right. Shooting a fireball will resolve this situation.

**Expected Behavior**
Players should never lose keyboard input

**Steps to Reproduce**
1. Go to master branch
2. Any mode
3. Get a pick axe
4. Jump towards a wall you can climb, after you jump, while in the air, hold down on the fireball key.
5. Climb the ledge to the top
6. You will lose the ability to move left or right until you shoot a fireball

**Comment by Regulator13** [comment]
This needs better steps to reproduce. Finding when a bug occurs exactly can be most of the solution. Anyone who can determine when exactly this occurs please post it.

**Comment by Regulator13** [comment]
I've found the steps to reproduce and edited the issue accordingly

**Comment by afrey15** [comment]
Haha, there is no way that is the only situation this occurs in based on how many times it has happened to me, but seems like a good start.

**Comment by Regulator13** [comment]
Okay finally got steps to reproduce correct. I will update the post again.

**Comment by afrey15** [comment]
Now THAT, I believe

**Comment by Regulator13** [comment]
This is all caused by an artifact that I was uncertain about before but left in there. This line:
```
if (!left_action_is_pressed and !right_action_is_pressed) or has_jetpack{
```
Which states you can't be holding down on the fire or ice button while moving left or right. If there a reason for this I will find a workaround, otherwise I'll just delete this line.

**Comment by afrey15** [comment]
Fascinating. Post on the Hangouts if you want that quick answer fix?

**Comment by Regulator13** [comment]
Yeah, that was the thought.

**Comment by Regulator13** [comment]
That way it'll only take half a day instead of never happen
