### ISSUE TITLE
Clicking on buttons in the menus

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#157]
**Context** 
I could be wrong, but I swear you can click on some buttons on the menu. There are some you definitely can't click on.

**Idea**
If it does in fact exist for some buttons, please make it so that you can use the mouse to click on all buttons in the menu. That would be very cool.

**Comment by Phabbits** [comment]
All menu buttons should be mouse clickable, there was a recent problem with the quit problem that was fixed with my latest pull request. If you find a specific button that you cannot click, let us know.
