### ISSUE TITLE
You fall off if you climb down from the top edge of a ledge with a pick

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#176]
**Bug**
If you are holding a pick and you stand on the edge of a ledge and press down, rather than hanging from the ledge, you will transport down and fall.

**Expected Behavior**
You should hang from the ledge

**Steps to Reproduce**
- Master branch, any mode
- Hold a pick
- Stand on the edge of a ledge
- Press down

**Comment by Regulator13** [comment]
I don't have the issue. It may have been inadvertently fixed.
