### ISSUE TITLE
Improved explosive blocks

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#187]
**Context** 
Explosive blocks are hard to use and dangerous. They don't need to be.

**Idea**
Increase the timer for explosive blocks back to 3 seconds. Reduce the explosion radius to 10 pixels so that it will never destroy more than 2 blocks in a row. Leave the explosion sprite as is.

**Comment by Regulator13** [comment]
3 seconds is good, but the block should also freeze in place and then wait 3 more seconds before exploding so the player has time to not be crushed by falling blocks

**Comment by afrey15** [comment]
If the block is going to freeze in place, I think we can keep the timers the same and just add those 3 seconds before exploding.

**Comment by Regulator13** [comment]
Yeah that sounds good

**Comment by Regulator13** [comment]
Should the block have to stick to something (it could stick to ceilings as well) or should it just freeze in mid-air?
