### ISSUE TITLE
Two yellow particles appear in the center of the screen, slightly on the right side

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#188]
**Bug**
We noticed it in a single player game. Two yellow flashing little particles would sometimes appear on the screen.

**Expected Behavior**
These should not exist.

**Comment by Regulator13** [comment]
This needs recreation steps.

**Comment by afrey15** [comment]
I have no idea on the recreation. Feel free to add it though if you figure it out. I didn't want it to be forgotten.

**Comment by Regulator13** [comment]
It may have just been your computer. We don't want issues on here that can't be fixed so can I think I'll close this issue unless you know what was causing it. We can reopen later if it occurs again.

**Comment by afrey15** [comment]
Okay

**Comment by Regulator13** [comment]
I had this issue after playing my lvl 35 run. I could not identify what caused it but 4 or 5 dots appeared in the middle of the screen that looked like the particles for the iceballs. I think the issue may be that they are not destroyed properly in some events.

**Comment by afrey15** [comment]
Ooh, interesting theory.. Yellow is one of the colors in the fireball particles. It seems likely
