### ISSUE TITLE
Change shooting direction to better meet player expectations

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#194]
**Context** 
No matter the input method, it feels as if fireballs and iceballs are firing at a lower arc than what they should. Of course, they are firing in the direction you specify, but that direction does not take into account the fact that people are looking beyond their immediate location when they fire.

**Idea**
Modify the direction specifications for firing so that the direction you specify indicates the location that the ball will be at several blocks out from the character rather than having it specify just the initial direction of the character.

**Comment by Regulator13** [comment]
Sounds good.

**Comment by Regulator13** [comment]
I'll try and make the fire/iceball pass through the intersecting point of the line from the player to the mouse and a circle 2 big blocks in radius centered on the player

**Comment by afrey15** [comment]
I cannot begin to fathom the complex math involved in this. Good luck
