### ISSUE TITLE
Double inputs being created

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#195]
**Bug**
This bug was first noticed with players using controllers. For a brief time, this bug did not exist. When players using controller input are on the team/character selection menu and they press their repsective `join` key, it creates two profiles and subsequently, they have two characters in the game. This could be related to #196.

**Expected Behavior**
Players should only create one profile when they join

**Steps to Reproduce**
1. Go to I believe `master` branch
2. Enter the player selection menu as controller input (you may need to be the second player)
3. Press `Start` or the respective key to join

**Comment by Regulator13** [comment]
This is definitely caused by #196. Fix that one instead.
