### ISSUE TITLE
Change jumping heights and strength so players are not hindered by most items

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire_and_ice#217]
**Context** 
Right now players pick up items and can mostly jump the same. However, since players also crouch when holding an object, and since the hanging effect accurately makes sure the players hands (lower when crouched) are near the ledge the player cannot technically jump as high. Some items that shouldn't also seem to hinder the player's jumping.

**Idea**
Make sure the default player (grinch) can grab a ledge just as high up with or without a block. This would probably include giving a tiny extra boost to jumping with an item so the players hands can still reach the edge.

**Reasoning**
I often leave items or blocks behind just because they slow down my jumping, sadly the most common one I leave is the hang-glider because for some reason it hinders the players jump. This should not be happening.

**Comment by afrey15** [comment]
I would say just increase the overall jump but this may be a better solution.

**Comment by Regulator13** [comment]
I would like to do that too. But I think keeping the jump the same with or without an item is important as well

**Comment by afrey15** [comment]
Your solution feels both counter intuitive and possibly a better solution than increasing the overall jump.
