### ISSUE TITLE
Players cannot climb a ledge with a block?

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#219]
**Context** 
I was wondering about your guy's opinion on this. I have found it frustrating each time I try to hang on a ledge and there is a block right on the edge and I'm like, "Why can't I hang there?!?"

**Idea**
Should we have a way to hang on the ledge at it's normal edge and ignore the block and then climb up it and like push the block out of the way?

**Comment by Regulator13** [comment]
Yeah. I guess we should
