### ISSUE TITLE
Create varied jump heights

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#229]
**Context** 
Player's used to control their jumps by using drag to correct them in situations where they absolutely needed to make smaller jumps. That is not so easy anymore but I think there is a better solution than how it worked anyway. Many games allow for some variance in your jump height by how long you press the jump key. I think we can do the same.

**Idea**
Create variable jump heights

**Reasoning**
This will allow player's to control their jumps more than ever before. It will also add a lot of player control that we didn't have.

**Steps to Implement**
I suggest measuring continuing to add to the vertical speed for a brief period after the key is pressed, up to a length that equals the player's current maximum height. However, there are tons of resources for this also:

Check out:
- https://www.reddit.com/r/gamemaker/comments/2usaao/dynamic_jump_heights_based_on_time_button_is/
- https://www.youtube.com/watch?v=cg4SyPSkqEo

**Comment by Regulator13** [comment]
This requires a key change but I'll give it a shot
