### ISSUE TITLE
Wall jumps

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire_and_ice#233]
**Context** 
The inability to change direction in mid-air may be a step in the right direction but it kills my flow sometimes.

**Idea**
A beautiful mechanic: wall jumps.

**Reasoning**
Help add flow back into game by giving the player the ability to make quick turns with the wall jump. It'll help reduce the amount of time players are dragging on the opposite button trying to stop so they can turn around. This isn't a problem for people when you jump 12 inches, but when you jump 5 times your height changing directions becomes a problem.

**Steps to Implement**
Do you have a plan of how to implement this? Why yes I do thanks for asking!

The implementation will be pretty simple, I want it to be automatic, that is, no stopping when you hit the wall or having to perfectly time button presses. The difficult part will be making sure player's don't wall jump when they don't want to. Here are my current requirements for a wall jump:

1. The player must be traveling upward (no downward jumps)
2. The player must be traveling at (or near) their max horizontal speed
3. The player must be off the ground when hitting the wall
4. The player must be holding the jump button when they hit a wall

The last one is to hopefully mitigate the issues of performing a wall jump when you mean to use a pick axe. I'm just going to test this, if it's not very natural I'll look for another solution.

**Comment by afrey15** [comment]
Sounds interesting

**Comment by afrey15** [comment]
Unfortunately I don't relate to it, quote "killing my flow"
