### ISSUE TITLE
Mouse aiming when mouse is in right walls

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire_and_ice#38]
**Describe the bug**
When aiming with the mouse in the right barrier walls, the shooting angle is always approximately 45 degrees, regardless of relative mouse position. For some reason this is not the case for the left wall

**To Reproduce**
1. Play game
2. Single player, any map
3. Go near the right wall and place your cursor in the right wall directly right of the player (0 degree angle)
4. The ball will fire at a 45 degree angle

**Expected behavior**
The ball should fire toward the mouse wherever it is

**Additional context**
Windows 10

**Comment by afrey15** [comment]
I encountered this glitch the other day when I played. I found it very strange. This may have to do with views. Perhaps the game believes that the mouse is in a different location because it is in a different viewport, namely the one with the character displays.

**Comment by Regulator13** [comment]
I thought about that @afrey15 but can't figure out how this would have an affect or where to fix that issue

**Comment by afrey15** [comment]
We suspect that the mouse coordinates may be incorrectly altered with the viewport. I have discovered a function called `window_view_mouse_get_y()`, and `window_view_mouse_get_x()` respectively. This function will return mouse coordinates relative to a specific viewport. By changing the current mouse coordinate retrieval to this command, we may be able to correct the way that GML reads the coordinates and put this issue to rest.

**Comment by Regulator13** [comment]
This actually worked. Not to sound surprised or anything.
