### ISSUE TITLE
Throwing other players

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire_and_ice#44]
**Context** 
Cooperative mode challenges players to get as far as they can as a team. In the game, almost anything can be thrown, different distances depending on their mass.

**Problem or idea**
Make it possible to throw players (if it's not already) so you can help your teammates out. This would also give meaning to the character's mass.

**Solution or next step**
Add throwing players and consider adjustments to #42 accordingly.

*Include any tags that apply. Tag a person if you are looking for a response from someone specific.*
Looking at @Phabbits on this since he has done it in the past.

**Comment by afrey15** [comment]
Likey

**Comment by Regulator13** [comment]
I really appreciate the comments because seeing other people's names reminds me I didn't type a 30 page contributing file for nothing, but you can also use the thumbs up emoji under the +:smiley: at the top of a comment to indicate you like or dislike an idea

**Comment by Regulator13** [comment]
I'll be posting a file under a code listing the current stats of items and characters just to help keep track of things
