### ISSUE TITLE
Create fireball and iceball animation

### ISSUE THREAD

**Issue by afrey15** [famegames/fire_and_ice#90]
**Context** 
The fire and ice balls are incredibly boring little circles with bizarre squares in them. I fall asleep looking at them sometimes.

**Idea**
Fireballs should have little flamey particle trails. Iceballs should have sparkly ice-crystal particle trails.

**Comment by Regulator13** [comment]
Mayyyybe a more descriptive title wouldn't hurt

**Comment by afrey15** [comment]
ftfy

**Comment by Regulator13** [comment]
thanks

**Comment by Regulator13** [comment]
Don't forget to add the animation switch on this for less powerful computers
